server:
  port: 9401
spring:
  # mysql配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: cqs
    password: 123456
    url: jdbc:mysql://154.9.26.115:3306/upload_file?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
    # 连接池配置
    druid:
      max-active: 20
      min-idle: 5
      initial-size: 5
      max-wait-thread-count: 20
  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB
      max-file-size: 100MB
      file-size-threshold: 20MB
  data:
    redis:
      database: 0
      host: 154.9.26.115
      port: 6379
      timeout: 30000
      client-type: lettuce
      password:
      lettuce:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 10
          min-idle: 0
# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cqs.entity

# 日志文件
logging:
  level:
    com:
      cqs: debug

file:
  url: /home/file